[project]
name = "mcp-google-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-api-python-client>=2.166.0",
    "google-auth-oauthlib>=1.2.1",
    "mcp[cli]>=1.6.0",
]
